server:
  port: 8080

spring:
  datasource:
    url:  jdbc:${DB_TYPE}://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Spring Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /system
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
