server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_URI}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
