server:
  port: 8080

spring:
  datasource:
    url:  jdbc:h2:mem:testDB
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:test/data.sql

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Spring Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /system
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
