server:
  port: 8080 # 내장 톰캣 포트

spring:
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:h2:mem:${DB_NAME}'   # H2 DB 연결 주소 (In-Memory Mode)
    username: ${DB_USER}      # H2 DB 접속 ID (사용자 지정)
    password: ${DB_PASS}  # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소
      settings:
        web-allow-others: true

  # JPA 설정
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: always
      data-locations: classpath:test/data.sql
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Spring Actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /system
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
