version: '1'

services:
  mysql:
    container_name: foodDB
    image: mysql/mysql-server:8.0.32
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'